substitutions:
  _REGION: "us-central1"
  _IMAGE_NAME: "python-app"

steps:

# 1. Build Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - "-t"
    - "us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}"
    - "./app"

# 2. Push image to Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args:
    - push
    - "us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}"

# 3. Replace image name inside k8s/deployment.yaml
- name: "ubuntu"
  entrypoint: bash
  args:
    - "-c"
    - |
      sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}|g" k8s/deployment.yaml

# 4. Commit and push updated deployment.yaml back to GitHub
- name: "gcr.io/cloud-builders/git"
  entrypoint: bash
  args:
    - "-c"
    - |
      git config --global user.email "rachanack123@gmail.com"
      git config --global user.name "rachanack-rachhu"
      git add k8s/deployment.yaml
      git commit -m "Update image to ${SHORT_SHA}"
      git push

# 5. Notify ArgoCD to refresh (Optional but recommended)
- name: "curlimages/curl"
  entrypoint: curl
  args:
    [
      "-X",
      "POST",
      "http://ARGOCD_SERVER/api/v1/applications/python-app/refresh"
    ]
