substitutions:
  _REGION: "us-central1"
  _IMAGE_NAME: "python-app"

options:
  logging: CLOUD_LOGGING_ONLY

steps:

# 1. Build Docker image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}", "./app"]

# 2. Push image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}"]

# 3. Update deployment.yaml (optional if using ArgoCD image updater)
- name: "ubuntu"
  entrypoint: bash
  args:
    - "-c"
    - |
      sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/thematic-land-477215-a5/python-repo/${_IMAGE_NAME}:${SHORT_SHA}|g" k8s/deployment.yaml

# ❗ REMOVED — No git push (this caused your error)
