substitutions:
  _REGION: "us-central1"
  _IMAGE_NAME: "python-app"

options:
  logging: CLOUD_LOGGING_ONLY

steps:

# 1. Build Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/python-repo/${_IMAGE_NAME}:${SHORT_SHA}",
      "./app"
    ]

# 2. Push Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/python-repo/${_IMAGE_NAME}:${SHORT_SHA}"
    ]

# 3. Update deployment.yaml
- name: "ubuntu"
  entrypoint: bash
  args:
    - "-c"
    - |
      sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/$PROJECT_ID/python-repo/${_IMAGE_NAME}:${SHORT_SHA}|g" k8s/deployment.yaml
